### ISSUE TITLE
Ad-Hocing with Pis

### ISSUE THREAD

**Issue by shantanoo-desai** [PiVersify/blog_posts#3]
Hi,
I love the idea of this blog and currently I am doing a lot of work with WiFi Dongles and **Ad-hoc mode** for Raspberry Pis. I have done a some work on it and would like to share my insight on the topic.

Would you prefer to have this on the blog ? Would be happy to contribute to the blog and the community.

**Comment by jacobm001** [comment]
I would be very happy to have community contributed articles. Go ahead and fork the _draft_ branch, and add an entry to it. Once you're ready, make a pull request, and we'll review it and schedule a time for it to be posted.

Feel free to write one or more articles!

**Comment by srpsco** [comment]
Jacob, 
We may get contributions from someone not familiar with github/git I would add that they can also submit a txt/word/html document.

Thanks,
Steve
